os:
  - linux
  - osx

osx_image: xcode9.0

language: node_js

node_js: 8

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

after_failure:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - artifacts upload $(git ls-files -o | grep -Fv -e node_modules -e dist -e app -e e2e)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then artifacts upload /*.log); fi

install:
  - yarn install

script:
  - node --version
  - yarn --version
  - yarn run e2e
  - yarn run dist


deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
