os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode10

language: node_js
node_js: 8

services:
  - docker

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

after_failure:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - artifacts upload $(git ls-files -o | grep -Fv -e node_modules -e dist -e app -e e2e)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then artifacts upload /*.log); fi

install:
  - yarn

script:
  - node --version
  - yarn --version
  - yarn commitlint-travis
  - yarn lint
  - yarn test
  - yarn build:prod
  - yarn e2e
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        yarn release
      fi
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker run --rm \
          --env-file <(env | grep -vE '\r|\n' | grep -iE 'NAME|DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CSC_|_TOKEN|_KEY|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          -v ${PWD}:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine-02.17 \
          /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
      fi
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

notifications:
  email:
    on_success: never
    on_failure: change
