os:
  - linux
  - osx

language: node_js

node_js: 8

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

after_failure:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - artifacts upload $(git ls-files -o | grep -Fv -e node_modules -e dist -e app -e e2e)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then artifacts upload $(ls $(npm config get cache)/_logs/); fi

script:
  - node --version
  - npm --version
  - npm install
  - npm run e2e

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
